# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-20 21:26
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("form_manager", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="InfoTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done_quantity", models.IntegerField()),
                ("remain_quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TemplateType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="form_manager.TemplateType",
            ),
        ),
        migrations.AddField(
            model_name="infotemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="form_manager.Template"
            ),
        ),
        migrations.AddField(
            model_name="infotemplate",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="form_manager.TemplateType",
            ),
        ),
    ]
