# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-05 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_manager', '0002_auto_20190720_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='form_manager.UserProfile'),
        ),
    ]
