# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-08 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("form_manager", "0003_userprofile_manager")]

    operations = [
        migrations.AddField(
            model_name="template",
            name="set_id",
            field=models.CharField(null=True, max_length=36),
        ),
        migrations.AddField(
            model_name="template",
            name="set_name",
            field=models.CharField(null=True, max_length=36),
        ),
    ]
