# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-12 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("form_manager", "0004_auto_20190808_0425")]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="uid",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        )
    ]
