# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-12 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form_manager', '0005_auto_20190812_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
