# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-12 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_manager', '0006_auto_20190812_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='gps',
            field=models.BooleanField(default=False),
        ),
    ]
