# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-08-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_manager', '0007_template_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='form_manager.UserProfile'),
        ),
    ]
