# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-29 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='motivo',
            new_name='reason',
        ),
    ]
