# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("form_manager", "0001_initial"),
        ("api", "0002_auto_20190629_1433"),
    ]

    operations = [
        migrations.RemoveField(model_name="formdata", name="access_date"),
        migrations.RemoveField(model_name="formdata", name="reason"),
        migrations.AddField(
            model_name="formdata",
            name="code",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="formdata",
            name="name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="formdata",
            name="uid",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name="formdata",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="form_manager.TemplateType",
            ),
        ),
    ]
