# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-28 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0004_formdata_user")]

    operations = [
        migrations.AddField(
            model_name="formdata",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="form_manager.Template",
            ),
        )
    ]
